### ISSUE TITLE
Buggregator server doesn't catch var-dumps in specific cases

### ISSUE THREAD

**Issue by roxblnfk** [buggregator/server#60] opened 2023-07-06 11:43 UTC
Buggregator server doesn't catch var-dumps in specific cases

For example, I installed `temporal/samples-php` project and
modified `\Temporal\WorkerFactory` (vendor package) like this:

```php
    public function run(HostConnectionInterface $host = null): int
    {
        $host ??= RoadRunner::create();
        $this->codec = $this->createCodec();

        while ($msg = $host->waitBatch()) {
            try {
                \dump($msg->messages, $msg->context);
                $response = $this->dispatch($msg->messages, $msg->context);
                \dump($response); // line 263
                $host->send($response);
            } catch (\Throwable $e) {
                $host->error($e);
            }
        }

        return 0;
    }
```

After `rr serve` Buggregator Server doesn't catch responses. But `buggregator/trap` does.
![{2A755B17-C290-41ED-ABAF-217CD3DD693B}](https://github.com/buggregator/server/assets/4152481/a48bbc8a-485c-4c40-955d-788e1643d4a7)

Need to research the problem.

**Comment by FluffyDiscord** [comment] 2023-09-06 10:51
By the payload size, it may be because it's reaching the default nginx proxy limit of 1MB which should be fixed with next release https://github.com/buggregator/server/pull/66

**Comment by roxblnfk** [comment] 2023-09-06 13:31
I'll check it. Thanks.

**Comment by roxblnfk** [comment] 2023-09-06 13:47
Now I have error messages like this:

```
2023-09-06T13:41:32.481Z        ERROR   app             TypeError: Spiral\RoadRunnerBridge\Centrifugo\Broadcast::publish(): Argument #2 ($messages) must be of type iterable|string, bool given, called in /app/app/src/Application/Broadcasting/BroadcastEventInterceptor.php on line 28 in /app/vendor/spiral/roadrunner-bridge/src/Centrifugo/Broadcast.php at line 17 [] []
```

And missed messages.

**Comment by FluffyDiscord** [comment] 2023-09-06 13:53
probably due to dependency update https://github.com/buggregator/server/commit/6cdfe5408c338b715202b7b627b0685c392679f9#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L43 @butschster

**Comment by butschster** [comment] 2023-09-07 11:31
Probably the problem is with payload, as I see it contains binary data, so when buggregator app tries to broadcast data

```php
$this->broadcast->publish(
    $event->getBroadcastTopics(),
    \json_encode([
        'event' => $event->getEventName(),
        'data' =>  $event->jsonSerialize(),
    ])
);
```

it endodes data into json and as I think, `json_encode` returns `false` when it tries to encode binary data

**Comment by FluffyDiscord** [comment] 2023-11-13 22:32
Just run into this issue. Any way for Buggregator to handle this correctly? VarDump shows the string binary correctly, adding the `b` indicator, just Buggregator seems to not be able to handle it.

**Comment by roxblnfk** [comment] 2023-11-26 19:54
Got it. I've reproduced it using Buggregator logo

**Closed** 2023-12-01 18:17 UTC
Labels: bug, c: difficult, module [var-dump]
