### ISSUE TITLE
Ray Dump support

### ISSUE THREAD

**Issue by menthol** [buggregator/server#24] opened 2023-03-25 09:41 UTC
Hello,

I don't see the compatibility with Ray dump anymore, did you remove it? 
Is it planned in a future version?

**Comment by butschster** [comment] 2023-03-25 10:19
Hi! Yes, it's planned after we bring in order a new frontend. Maybe in 2 weeks.

**Comment by menthol** [comment] 2023-03-25 12:05
I can help for the frontend part

**Comment by butschster** [comment] 2023-04-26 15:27
https://myray.app/

**Comment by butschster** [comment] 2023-05-13 19:34
![image](https://github.com/buggregator/spiral-app/assets/773481/c2a84d40-fc99-4bde-b87f-ea81cc1daa17)

**Comment by butschster** [comment] 2023-05-13 19:37
Hi @menthol 
I've just finished working on module https://github.com/buggregator/spiral-app/pull/43. I didn't finish only `mailable` type. If you want you can try to finish and maybe polish frontend. There is storybook with all required mocks for ray components

**Comment by Semdevmaster** [comment] 2023-05-16 07:31
Ray integration in Laravel doesn't work in any recent releases: dev, lastest, rc
I am using docker and compose

docker-compose.yml
```yml
    buggregator:
      image: ghcr.io/buggregator/server:dev
      container_name: buggregator-${APP_HOST}
      ports:
        - 8000:8000
      networks:
        - docker-server
```

.env part
```env
RAY_HOST=buggregator
RAY_PORT=8000
```
The ray() function works in the code, but the buggregator interface is empty, while Symphony var_dumper works fine!

**Comment by butschster** [comment] 2023-05-20 19:51
@Semdevmaster I've just release a new version, could you try it?

**Comment by HydroMoon** [comment] 2023-05-21 11:40
@butschster I can confirm still this issue exist.

```
MacOs
.env
RAY_HOST=host.docker.internal
RAY_PORT=23517

Nothing appear in log however SMTP is working fine with:
MAIL_HOST=host.docker.internal
MAIL_PORT=1025
```

![image](https://github.com/buggregator/server/assets/9692083/62e45995-6323-4f7a-a306-04bb8e9315ae)

This is when used with javascript. When used with Laravel nothing happen on the output

**Comment by Semdevmaster** [comment] 2023-05-22 04:02
> @Semdevmaster I've just release a new version, could you try it?

Check rc-4 - error still exists

**Comment by daronspence** [comment] 2023-06-09 19:41
Hi, might be unrelated, but i notice that eloquent models are sent with `->toArray()` in Buggregator. Is this intentional?

I see it has an `eloquent_model` tag but that doesn't help much when using Polymorphism in the calling location :( 

Maybe I have a setting incorrectly applied? I'm using the docker compose install method.

<img width="638" alt="CleanShot 2023-06-09 at 21 40 22@2x" src="https://github.com/buggregator/server/assets/4062087/04313589-3d41-41de-a275-52abe9be56d5">

**Comment by FluffyDiscord** [comment] 2023-06-12 10:36
Any updates on this?

**Comment by butschster** [comment] 2023-11-24 22:03
I think the problem was solved and I can close the issue. If someone has a new problems, let me know! Thx for help! [Join our discord](https://discord.gg/vDsCD3EKUB)!

**Closed by butschster** 2023-11-24 22:03 UTC
Labels: help wanted, question, module [Ray]
